service APIName where

datatype Name       = Text
datatype Age        = Int
datatype Address    = Text
datatype Birthday   = DateTime

resource Person =
    {   name : Name
    ,   age : Age
    ,   address : Address
    ,   parent_address : Address
    }

GET /person/ :
    Returns : ListOf Person in JSON
    Description : "Gets the list of Persons stored on the server"
    Parameters : None
    Errors : None
    Notes : "Nothing."
end

POST /person/ :
    Returns : Person in JSON
    Description : "Allows the Client to push Persons to the server, returns a copy of the stored representation"
    Parameters : None
    Body : Person in JSON
    Errors :
        400 : "The Client has sent an incorrect representation."
    Notes : "Still Nothing."

GET /person/{id}
    Returns : Person in JSON
    Description : "Retrieves the Person resource with the given id."
    Parameters :
        id : "The ID for the desired Person resource"
    Errors :
        404 : "If no Person exists with that ID"
    Notes : "Nothing Again.."
End

PUT /person/{id}:
    Returns : Person in JSON
    Description : "Updates the Address or Age for the specified Person"
    Parameters :
        id : "The ID for the desired Person resource"

    Body :
        {   age : Age
        ,   address : Address
        } in JSON
    Errors :
        400 : "No Person exists with the given ID"

    Notes : "Names are not allowed to change."
End

DELETE /person/{id}:
    Returns : Nothing
    Description : "Deletes a Person"
    Parameters :
        id : "The ID for the desired Person resource"

    Body :
        {   age : Age
        ,   address : Address
        } in JSON

    Errors :
        400 : "No Person exists with the given ID"

    Notes : "Names are not allowed to change."
End

