`APIName` servesDataTypes
    [   Name : Text
    ,   Age : Int
    ,   Address : Text
    ,   Birthday : DateTime
    ]

inResources
    (   Person
        [   Name
        ,   Age
        ,   Address
        ]
    )

viaURIs
    (   GET /person/
        [   Returns : ListOf Person
        ,   Description : "Gets the list of Persons stored on the server"
        ,   Parameters : None
        ,   Errors : None
        ,   Notes : "Nothing."
        ]
    ,   POST /person/
        [   Returns : Person in JSON
        ,   Description : "Allows the Client to push Persons to the server, returns a copy of the stored representation"
        ,   Parameters : None
        ,   Body : Person in JSON
        ,   Errors :
            [   400 : "The Client has sent an incorrect representation."
            ]
        ,   Notes : "Still Nothing."
        ]
    ,   GET /person/{id}
        [   Returns : Person in JSON
        ,   Description : "Retrieves the Person resource with the given id."
        ,   Parameters :
            [   id : "The ID for the desired Person resource"
            ]
        ,   Errors :
            [   404 : "If no Person exists with that ID"
            ]
        ,   Notes : "Nothing Again.."
        ]
    ,   PUT /person/{id}
        [   Returns : Person in JSON
        ,   Description : "Updates the Address or Age for the specified Person"
        ,   Parameters :
            [   id : "The ID for the desired Person resource"
            ]
        ,   Body :
            [   Age
            ,   Address
            ] in JSON
        ,   Errors :
            [   400 : "No Person exists with the given ID"
            ]
        ,   Notes : "Names are not allowed to change."
        ]
    ,   DELETE /person/{id}
        [   Returns : Nothing
        ,   Description : "Deletes a Person"
        ,   Parameters :
            [   id : "The ID for the desired Person resource"
            ]
        ,   Body :
            [   Age
            ,   Address
            ] in JSON
        ,   Errors :
            [   400 : "No Person exists with the given ID"
            ]
        ,   Notes : "Names are not allowed to change."
        ]
    )

